name: Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/nickpegg/md_wiki_to_html
    - name: Build
      run: |
        make build

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Publish
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: '.output'
        destination: 'wiki.nickpegg.com'
        parent: false
